### ISSUE TITLE
Mux video input

### ISSUE THREAD

**Issue by RobEasthope** [ricokahler/sanity-codegen#145]
I'm using [Mux's Sanity input plugin](https://www.sanity.io/plugins/sanity-plugin-mux-input) to host video but sanity-codegen is throwing an issue due to the fullstop in the name:

```Error: Name "mux.video" is not valid. Ensure camel case, alphanumeric, and underscore characters only```

Is there a way to ignore or alias the plugin when generating types?

**Comment by ricokahler** [comment]
I think you've caught a valid use case of `.` in an identifier. I think the best path forward is to allow full stops if it's used as a `type` (vs a `name`). I can have this out soon. Thanks for catching it!

**Comment by ricokahler** [comment]
Fixed in [v0.9.4](https://github.com/ricokahler/sanity-codegen/releases/tag/v0.9.4). Thanks a bunch!

**Comment by RobEasthope** [comment]
Perfect, thanks @ricokahler and thanks for your work on the plugin, it's been a great help
