### ISSUE TITLE
Usage with custom input components that depend on browser APIs

### ISSUE THREAD

**Issue by ricokahler** [ricokahler/sanity-codegen#214]
### Discussed in https://github.com/ricokahler/sanity-codegen/discussions/207

<div type='discussions-op-text'>

<sup>Originally posted by **danmichaelo** October 15, 2021</sup>
Hi! We've just getting started with creating our own custom input components for a Next.js Sanity Studio project, more specifically a date picker based on https://react-day-picker.js.org/ , but this caused `sanity-codegen` to stop working because there is some dependency on a browser API:

```bash
> npx sanity-codegen

ReferenceError: window is not defined
    at Object.<anonymous> (/home/runner/work/sanity-demo/sanity-demo/sanity/node_modules/@sanity/base/lib/util/resizeObserver.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/home/runner/work/sanity-demo/sanity-demo/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/home/runner/work/sanity-demo/sanity-demo/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/runner/work/sanity-demo/sanity-demo/sanity/node_modules/@sanity/base/lib/change-indicators/overlay/useResizeObserver.js:10:23)
```

Guess we're not the first ones running into this problem, but didn't find a solution when googling, so would be awesome if someone could share how they worked around this 🙏 Some kind of lazy-loading perhaps?

Our `sanity-codegen.config.ts` is really simple atm.:

```javascript
import { SanityCodegenConfig } from "sanity-codegen";

const config: SanityCodegenConfig = {
  schemaPath: "./sanity/schemas/schema",
  outputPath: "./generatedTypes/modelTypes.ts",
};

export default config;
```</div>

**Comment by ricokahler** [comment]
Creating an issue to follow up on this. I think it makes sense to shim out browser APIs

**Comment by joeswann** [comment]
Seem to be getting this issue on the alpha branch!

**Comment by jfulse** [comment]
Hello, thanks for a great library!

We're seeing this issue and have been using a workaround where a script stubs out custom input components before running the script.

At the moment, however, the issue comes from somewhere else and we're not sure how to approach it. The stack trace is as follows:

```
    Error: {
      "message": "window is not defined",
      "stack": "ReferenceError: window is not defined\n    at Object.<anonymous>
    ([REPO_PATH]/sanity/node_modules/@sanity/base/lib
    /util/resizeObserver.js:14:22)\n    at Module._compile
    (node:internal/modules/cjs/loader:1101:14)\n    at Module._compile (/Users/jorgen
    fulsebakke/repos/libry-content/node_modules/pirates/lib/index.js:136:24)\n    at
    Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n    at
    Object.newLoader [as .js] ([REPO_PATH]/node_modul
    es/pirates/lib/index.js:141:7)\n    at Module.load
    (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load
    (node:internal/modules/cjs/loader:822:12)\n    at Module.require
    (node:internal/modules/cjs/loader:1005:19)\n    at require
    (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous>
    ([REPO_PATH]/sanity/node_modules/@sanity/base/lib
    /change-indicators/overlay/useResizeObserver.js:10:23)"
}
```

Do you have any tips for how to resolve this?

We've tested versions `v1.0.0-alpha.8`, `0.9.8` and `0.9.5`, with `@sanity/cli v2.27.0`

**Comment by devinhalladay** [comment]
@joeswann any updates on whether this is resolved in the alpha?
