### ISSUE TITLE
Process hangs on M1 Mac

### ISSUE THREAD

**Issue by alexbchr** [ricokahler/sanity-codegen#232]
We just got a new M1 Mac for someone on our team and everything in our codebase works fine except the `sanity-codegen` CLI. `sanity-codegen` has been setupped for quite a while in this project and is working fine on every Mac and Windows machine, except the Mac with the M1 processor.

We're using the latest version of sanity-codegen (0.9.8).

Basically when executing `sanity-codegen`, the process simply doesn't do anything. Nothing gets printed in the Terminal and we are simply executing `yarn sanity-codegen`.

**Comment by ricokahler** [comment]
Ah very interesting. As far as I'm aware, this package doesn't use any sort of dependencies that wouldn't work on an M1 mac (no native etc) so I don't have any hunches atm. Have you also tested this one non-M1 machines on a fresh install (i.e. delete node_modules + lock files)?

I also have an M1 mac. If you can set up a reproduction, I can give it a try myself.

**Comment by alexbchr** [comment]
Quick follow-up here. I still have no idea what the issue is honestly, but we received another M1 Max laptop this week and can confirm that the issue is not the M1 chip. 

I'll investigate a bit more on our end to check what the issue could be and I'll close this for now. Once I get a better understanding of the issue I may open another issue with more details, if relevant to sanity-codegen.

Sorry for the trouble and thanks again for the help!
