### ISSUE TITLE
TS2503: Cannot find namespace 'Sanity'

### ISSUE THREAD

**Issue by goodwin64** [ricokahler/sanity-codegen#314]
Using the same approach as in [README](https://github.com/ricokahler/sanity-codegen/blob/alpha/README.md?plain=1#L33-L35):
```
interface Props {
  book: Sanity.Default.Schema.Book; // no import needed. just use it
}
```

I do the same in my code but it doesn't give me proper types:
```
const url = `https://${this.projectId}.api.sanity.io/v2021-10-21/data/query/${this.dataset}?query=${QUERY}`;

// fetch the content
const result = await fetch(url)
  .then((res) => res.json())
  .then(({ result }: { result: Sanity.Default.Schema.Adventure[] }) => {
    const firstAdventure = result[0];
    console.log(firstAdventure.adventureCode); // Intellisense doesn't show the type
    console.log(firstAdventure.contactNumberDestination); // nor here
    return result;
  });

return result;
}
```

moreover, ESlint complains to the Sanity namespace being not found:
![image](https://github.com/ricokahler/sanity-codegen/assets/10671879/692e2011-0045-42fb-a858-731db51e9834)

Are there any TS config changes needed to be done additionally to recognise the Sanity namespace?

**Comment by ochicf** [comment]
Hi @goodwin64!

The `Sanity` namespace is added by `@sanity-codegen/types`, and then augmented by the types generated by the codegen (adding your namespace and your types).

So I would say that you need to make sure that:
- `@sanity-codegen/types` is installed as dev dependency (or at least present by some other dependency)
- the file with the generated types is included by your `tsconfig.json`

Hope that helps!

(full disclaimer: I also have problems with certain typings, as stated here https://github.com/ricokahler/sanity-codegen/issues/298)

**Comment by goodwin64** [comment]
Heyyy @ochicf! Thanks for the reply!

We've made it a slightly different way eventually - moved our types to GraphQL schema so we just need to update it there (needed by arch req-s).

But yeah, compared to how easy it was to setup a Sanity client and fill in the content, the type-gen process feels a bit raw.

**Comment by goodwin64** [comment]
Closing as not relevant but feel free to reopen later/link other issues here.
