### ISSUE TITLE
Sanity array of objects is missing a _key prop

### ISSUE THREAD

**Issue by PaulPCIO** [ricokahler/sanity-codegen#54]
If you add an array to your dataset the data would include a `_key:string` using a unique id for that array item.

When querying your data you might want to reference a specific array item using it's key.

Currently the codegen returns Array<TYPE>  which is technically incorrect.

Maybe something like this could do the trick?

```typescript
type SanityArray<T> = Array<T & {_key:string}>
```

An [ example ](https://www.sanity.io/docs/array-type#example-array-containing-both-crew-members-and-cast-members-h55yDoQL) showing the output data with the _key

**Comment by ricokahler** [comment]
Thanks for bringing this up. My coworker (cc @dsifford) actually brought up this same exact idea with the same name too lol.

I would be accepting PRs for this if you'd be willing to give it a whirl. Otherwise, I think I can get to this sometime tomorrow.

**Comment by PaulPCIO** [comment]
Haha you know what they say, "great mind think alike" :rofl: :rocket: 

I would have loved to do a pr but unfortunately i'm a little tied up in a sprint this week. :hourglass:

**Comment by ricokahler** [comment]
This idea worked with a slight modification.

I tried doing

```
type Sani
```

However, that produced errors like this:

```
```
